"""
PDF Report Generator
Produces boardroom-quality threat intelligence reports using ReportLab.
"""

import os
from datetime import datetime
from typing import Dict, Any

try:
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import cm, mm
    from reportlab.lib.colors import (HexColor, black, white, Color)
    from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer, Table,
                                    TableStyle, HRFlowable, PageBreak, KeepTogether)
    from reportlab.graphics.shapes import Drawing, Rect, Circle, String, Polygon
    from reportlab.graphics.charts.piecharts import Pie
    from reportlab.graphics import renderPDF
    from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT
    REPORTLAB_AVAILABLE = True
except ImportError:
    REPORTLAB_AVAILABLE = False


# Color Palette
C_BG = HexColor("#0D0F14") if REPORTLAB_AVAILABLE else None
C_SURFACE = HexColor("#161B25") if REPORTLAB_AVAILABLE else None
C_ACCENT = HexColor("#00D4FF") if REPORTLAB_AVAILABLE else None
C_CRITICAL = HexColor("#FF3B3B") if REPORTLAB_AVAILABLE else None
C_HIGH = HexColor("#FF7A00") if REPORTLAB_AVAILABLE else None
C_MEDIUM = HexColor("#FFB800") if REPORTLAB_AVAILABLE else None
C_LOW = HexColor("#00C853") if REPORTLAB_AVAILABLE else None
C_TEXT = HexColor("#E8EAF0") if REPORTLAB_AVAILABLE else None
C_MUTED = HexColor("#8892A4") if REPORTLAB_AVAILABLE else None



DISCLAIMER = (
    "IMPORTANT — FOR RESEARCH & EDUCATIONAL USE ONLY: "
    "This report is generated by an automated OSINT aggregation tool. "
    "Findings are based on publicly available data and may be incomplete or inaccurate. "
    "Risk scores are heuristic estimates trained on synthetic data — they are NOT certified "
    "security assessments and carry no guarantee of accuracy. "
    "Do NOT make security, legal, financial, or operational decisions based solely on this output. "
    "Always verify findings with a qualified, licensed security professional. "
    "Only scan domains you own or have explicit written permission to assess. "
    "Unauthorised scanning may violate applicable laws."
)


class ReportGenerator:
    def __init__(self, domain: str, company: str, findings: dict, scores: dict):
        self.domain = domain
        self.company = company
        self.findings = findings
        self.scores = scores
        self.report_dir = "/tmp/reports"
        os.makedirs(self.report_dir, exist_ok=True)

    def generate(self, job_id: str) -> str:
        path = os.path.join(self.report_dir, f"report_{job_id[:8]}.pdf")

        if not REPORTLAB_AVAILABLE:
            # Fallback: create a simple text report
            return self._generate_text_report(path.replace(".pdf", ".txt"))

        doc = SimpleDocTemplate(
            path,
            pagesize=A4,
            leftMargin=2*cm, rightMargin=2*cm,
            topMargin=2*cm, bottomMargin=2*cm,
        )

        story = []
        story += self._cover_page()
        story.append(PageBreak())
        story += self._executive_summary()
        story += self._risk_scorecard()
        story += self._findings_sections()
        story += self._recommendations()
        story += self._appendix()

        doc.build(story, onFirstPage=self._add_header_footer,
                  onLaterPages=self._add_header_footer)
        return path

    def _styles(self):
        styles = getSampleStyleSheet()
        custom = {
            "h1": ParagraphStyle("h1", fontName="Helvetica-Bold", fontSize=24,
                                  textColor=C_ACCENT, spaceAfter=12, leading=30),
            "h2": ParagraphStyle("h2", fontName="Helvetica-Bold", fontSize=16,
                                  textColor=C_TEXT, spaceAfter=8, spaceBefore=16, leading=22),
            "h3": ParagraphStyle("h3", fontName="Helvetica-Bold", fontSize=12,
                                  textColor=C_ACCENT, spaceAfter=6, spaceBefore=10),
            "body": ParagraphStyle("body", fontName="Helvetica", fontSize=10,
                                    textColor=C_TEXT, spaceAfter=6, leading=15),
            "muted": ParagraphStyle("muted", fontName="Helvetica", fontSize=9,
                                     textColor=C_MUTED, spaceAfter=4),
            "critical": ParagraphStyle("critical", fontName="Helvetica-Bold", fontSize=10,
                                        textColor=C_CRITICAL),
            "code": ParagraphStyle("code", fontName="Courier", fontSize=9,
                                    textColor=HexColor("#A8FF78"), backColor=HexColor("#0D1117"),
                                    spaceAfter=4, leftIndent=10, leading=14),
        }
        return custom

    def _add_header_footer(self, canvas, doc):
        canvas.saveState()
        w, h = A4

        # Top bar
        canvas.setFillColor(C_SURFACE)
        canvas.rect(0, h - 1.2*cm, w, 1.2*cm, fill=1, stroke=0)
        canvas.setFillColor(C_ACCENT)
        canvas.rect(0, h - 1.2*cm, 0.4*cm, 1.2*cm, fill=1, stroke=0)
        canvas.setFillColor(C_MUTED)
        canvas.setFont("Helvetica", 8)
        canvas.drawString(1*cm, h - 0.8*cm, f"CONFIDENTIAL — Attack Surface Report: {self.domain}")
        canvas.drawRightString(w - 1*cm, h - 0.8*cm, datetime.utcnow().strftime("%Y-%m-%d"))

        # Bottom bar
        canvas.setFillColor(C_SURFACE)
        canvas.rect(0, 0, w, 0.8*cm, fill=1, stroke=0)
        canvas.setFillColor(C_MUTED)
        canvas.setFont("Helvetica", 8)
        canvas.drawString(1*cm, 0.3*cm, "Generated by Corporate Attack Surface Mapper")
        canvas.drawRightString(w - 1*cm, 0.3*cm, f"Page {doc.page}")
        canvas.restoreState()

    def _cover_page(self):
        s = self._styles()
        elements = []

        elements.append(Spacer(1, 3*cm))
        elements.append(Paragraph("⚠ CONFIDENTIAL", ParagraphStyle(
            "conf", fontName="Helvetica-Bold", fontSize=11, textColor=C_CRITICAL,
            alignment=TA_CENTER, spaceAfter=8
        )))
        elements.append(Paragraph("CORPORATE ATTACK SURFACE", ParagraphStyle(
            "title1", fontName="Helvetica-Bold", fontSize=32, textColor=C_TEXT,
            alignment=TA_CENTER, spaceAfter=4, leading=38
        )))
        elements.append(Paragraph("INTELLIGENCE REPORT", ParagraphStyle(
            "title2", fontName="Helvetica-Bold", fontSize=32, textColor=C_ACCENT,
            alignment=TA_CENTER, spaceAfter=20, leading=38
        )))

        # Risk score badge
        overall = self.scores.get("overall", 0)
        risk_label = self.scores.get("risk_label", "UNKNOWN")
        risk_color = HexColor(self.scores.get("risk_color", "#888888"))

        badge_data = [[
            Paragraph(str(int(overall)), ParagraphStyle(
                "score", fontName="Helvetica-Bold", fontSize=48,
                textColor=risk_color, alignment=TA_CENTER
            )),
        ], [
            Paragraph(f"RISK SCORE — {risk_label}", ParagraphStyle(
                "scoreLabel", fontName="Helvetica-Bold", fontSize=14,
                textColor=risk_color, alignment=TA_CENTER
            )),
        ]]
        badge = Table(badge_data, colWidths=[8*cm])
        badge.setStyle(TableStyle([
            ("BACKGROUND", (0,0), (-1,-1), C_SURFACE),
            ("BOX", (0,0), (-1,-1), 2, risk_color),
            ("TOPPADDING", (0,0), (-1,-1), 12),
            ("BOTTOMPADDING", (0,0), (-1,-1), 12),
            ("ALIGN", (0,0), (-1,-1), "CENTER"),
        ]))
        elements.append(Table([[badge]], colWidths=[17*cm]))
        elements.append(Spacer(1, 1.5*cm))

        # Target info
        info_data = [
            ["TARGET DOMAIN", self.domain],
            ["COMPANY", self.company],
            ["SCAN DATE", datetime.utcnow().strftime("%B %d, %Y %H:%M UTC")],
            ["CRITICAL FINDINGS", str(self.scores.get("critical_issues", 0))],
            ["HIGH FINDINGS", str(self.scores.get("high_issues", 0))],
            ["TOTAL FINDINGS", str(self.scores.get("total_issues", 0))],
        ]
        info_table = Table(info_data, colWidths=[6*cm, 11*cm])
        info_table.setStyle(TableStyle([
            ("BACKGROUND", (0,0), (0,-1), C_SURFACE),
            ("FONTNAME", (0,0), (0,-1), "Helvetica-Bold"),
            ("FONTNAME", (1,0), (1,-1), "Helvetica"),
            ("FONTSIZE", (0,0), (-1,-1), 10),
            ("TEXTCOLOR", (0,0), (0,-1), C_ACCENT),
            ("TEXTCOLOR", (1,0), (1,-1), C_TEXT),
            ("TOPPADDING", (0,0), (-1,-1), 7),
            ("BOTTOMPADDING", (0,0), (-1,-1), 7),
            ("LEFTPADDING", (0,0), (-1,-1), 10),
            ("LINEBELOW", (0,0), (-1,-2), 0.5, C_SURFACE),
        ]))
        elements.append(info_table)
        elements.append(Spacer(1, 0.8*cm))

        # ── Disclaimer box ──────────────────────────────────────
        disclaimer_table = Table([[
            Paragraph(DISCLAIMER, ParagraphStyle(
                "disclaimer",
                fontName="Helvetica", fontSize=7.5,
                textColor=HexColor("#FFB800"),
                leading=11, spaceAfter=0,
            ))
        ]], colWidths=[17*cm])
        disclaimer_table.setStyle(TableStyle([
            ("BACKGROUND",    (0,0), (-1,-1), HexColor("#1A1500")),
            ("BOX",           (0,0), (-1,-1), 1, HexColor("#FFB800")),
            ("LEFTPADDING",   (0,0), (-1,-1), 10),
            ("RIGHTPADDING",  (0,0), (-1,-1), 10),
            ("TOPPADDING",    (0,0), (-1,-1), 8),
            ("BOTTOMPADDING", (0,0), (-1,-1), 8),
        ]))
        elements.append(disclaimer_table)
        return elements

    def _executive_summary(self):
        s = self._styles()
        elements = [Paragraph("Executive Summary", s["h1"])]
        elements.append(HRFlowable(width="100%", thickness=1, color=C_ACCENT))
        elements.append(Spacer(1, 0.3*cm))

        overall = self.scores.get("overall", 0)
        risk_label = self.scores.get("risk_label", "UNKNOWN")
        breach_prob = self.scores.get("breach_probability", 0)
        summary_text = (
            f"This report presents the results of an automated attack surface assessment conducted "
            f"against <b>{self.company}</b> ({self.domain}). The assessment leverages open-source "
            f"intelligence (OSINT) methodologies including DNS enumeration, Shodan port scanning, "
            f"certificate transparency analysis, GitHub secret detection, and HTTP security analysis.<br/><br/>"
            f"The target received a heuristic surface exposure score of <b>{int(overall)}/100</b>, "
            f"classified as <b>{risk_label}</b>. This score reflects the density and severity of "
            f"publicly observable security signals — it is NOT a prediction of breach likelihood "
            f"and carries no actuarial basis.<br/><br/>"
            f"A total of <b>{self.scores.get('total_issues', 0)} signals</b> were identified across "
            f"all assessment categories, including <b>{self.scores.get('critical_issues', 0)} critical</b> "
            f"and <b>{self.scores.get('high_issues', 0)} high-severity</b> signals that warrant "
            f"human review by a qualified security professional.<br/><br/>"
            f"<b>These findings represent publicly visible data only.</b> They do not reflect the "
            f"actual security posture, internal controls, or breach history of the organisation."
        )
        elements.append(Paragraph(summary_text, s["body"]))
        elements.append(Spacer(1, 0.3*cm))
        elements.append(Paragraph(
            "<b>Disclaimer:</b> " + DISCLAIMER,
            ParagraphStyle(
                "disc_body", fontName="Helvetica-Oblique", fontSize=8,
                textColor=HexColor("#FFB800"), leading=12, spaceAfter=6,
                backColor=HexColor("#1A1500"), leftIndent=8, rightIndent=8,
            )
        ))
        return elements

    def _risk_scorecard(self):
        s = self._styles()
        elements = [Spacer(1, 0.5*cm), Paragraph("Risk Scorecard", s["h1"])]
        elements.append(HRFlowable(width="100%", thickness=1, color=C_ACCENT))
        elements.append(Spacer(1, 0.3*cm))

        dimensions = self.scores.get("dimensions", {})
        headers = ["Category", "Score", "Risk Level", "Weight", "Description"]
        rows = [headers]

        for dim_key, dim_val in dimensions.items():
            score = dim_val.get("score", 0)
            label = dim_val.get("label", "")
            weight = f"{int(dim_val.get('weight', 0) * 100)}%"
            description = dim_val.get("description", "")
            name = dim_key.replace("_", " ").title()
            rows.append([name, f"{score:.0f}/100", label, weight, description])

        col_widths = [4.5*cm, 2*cm, 2.5*cm, 1.5*cm, 6.5*cm]
        table = Table(rows, colWidths=col_widths)

        severity_colors = {"CRITICAL": C_CRITICAL, "HIGH": C_HIGH, "MEDIUM": C_MEDIUM,
                           "LOW": C_LOW, "MINIMAL": HexColor("#00E5FF")}

        style = [
            ("BACKGROUND", (0,0), (-1,0), C_ACCENT),
            ("TEXTCOLOR", (0,0), (-1,0), black),
            ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),
            ("FONTSIZE", (0,0), (-1,-1), 9),
            ("TOPPADDING", (0,0), (-1,-1), 7),
            ("BOTTOMPADDING", (0,0), (-1,-1), 7),
            ("LEFTPADDING", (0,0), (-1,-1), 8),
            ("TEXTCOLOR", (0,1), (-1,-1), C_TEXT),
            ("ROWBACKGROUNDS", (0,1), (-1,-1), [C_BG, C_SURFACE]),
            ("GRID", (0,0), (-1,-1), 0.3, C_MUTED),
        ]
        for i, (_, dim_val) in enumerate(dimensions.items(), start=1):
            label = dim_val.get("label", "")
            color = severity_colors.get(label, C_MUTED)
            style.append(("TEXTCOLOR", (2,i), (2,i), color))
            style.append(("FONTNAME", (2,i), (2,i), "Helvetica-Bold"))

        table.setStyle(TableStyle(style))
        elements.append(table)
        return elements

    def _findings_sections(self):
        s = self._styles()
        elements = [PageBreak(), Paragraph("Detailed Findings", s["h1"])]
        elements.append(HRFlowable(width="100%", thickness=1, color=C_ACCENT))

        top_risks = self.scores.get("top_risks", [])
        if not top_risks:
            elements.append(Paragraph("No significant findings detected.", s["body"]))
            return elements

        severity_colors = {"CRITICAL": C_CRITICAL, "HIGH": C_HIGH, "MEDIUM": C_MEDIUM, "LOW": C_LOW}

        for i, finding in enumerate(top_risks):
            severity = finding.get("severity", "LOW")
            color = severity_colors.get(severity, C_LOW)
            title = finding.get("title", "Unknown Finding")
            description = finding.get("description", "")
            recommendation = finding.get("recommendation", "")
            category = finding.get("category", "").replace("_", " ").upper()

            row_data = [[
                Paragraph(f"[{severity}] {title}", ParagraphStyle(
                    f"find{i}", fontName="Helvetica-Bold", fontSize=10, textColor=color
                )),
                Paragraph(category, ParagraphStyle(
                    f"cat{i}", fontName="Helvetica", fontSize=8, textColor=C_MUTED, alignment=TA_RIGHT
                )),
            ]]
            header_table = Table(row_data, colWidths=[13*cm, 4*cm])
            header_table.setStyle(TableStyle([
                ("LEFTPADDING", (0,0), (-1,-1), 10),
                ("RIGHTPADDING", (0,0), (-1,-1), 10),
                ("TOPPADDING", (0,0), (-1,-1), 8),
                ("BOTTOMPADDING", (0,0), (-1,-1), 4),
                ("BACKGROUND", (0,0), (-1,-1), C_SURFACE),
                ("LINEBEFORE", (0,0), (0,-1), 3, color),
            ]))

            body_data = []
            if description:
                body_data.append([Paragraph(f"<b>Finding:</b> {description}", s["body"])])
            if recommendation:
                body_data.append([Paragraph(f"<b>Remediation:</b> {recommendation}", ParagraphStyle(
                    f"rec{i}", fontName="Helvetica", fontSize=10,
                    textColor=HexColor("#A8FF78"), spaceAfter=4, leading=15
                ))])

            if body_data:
                body_table = Table(body_data, colWidths=[17*cm])
                body_table.setStyle(TableStyle([
                    ("LEFTPADDING", (0,0), (-1,-1), 10),
                    ("RIGHTPADDING", (0,0), (-1,-1), 10),
                    ("TOPPADDING", (0,0), (-1,-1), 4),
                    ("BOTTOMPADDING", (0,0), (-1,-1), 8),
                    ("BACKGROUND", (0,0), (-1,-1), HexColor("#0D1117")),
                    ("LINEBEFORE", (0,0), (0,-1), 3, color),
                ]))
                elements.append(KeepTogether([header_table, body_table]))
            else:
                elements.append(header_table)
            elements.append(Spacer(1, 0.3*cm))

        return elements

    def _recommendations(self):
        s = self._styles()
        elements = [PageBreak(), Paragraph("Remediation Roadmap", s["h1"])]
        elements.append(HRFlowable(width="100%", thickness=1, color=C_ACCENT))
        elements.append(Spacer(1, 0.3*cm))

        critical_count = self.scores.get("critical_issues", 0)
        high_count = self.scores.get("high_issues", 0)

        phases = [
            ("Phase 1 — Immediate (0–7 days)", C_CRITICAL,
             f"Address all {critical_count} CRITICAL findings. Patch exposed services, rotate "
             f"any leaked credentials, and restrict dangerous open ports behind firewalls or VPNs."),
            ("Phase 2 — Short Term (7–30 days)", C_HIGH,
             f"Remediate {high_count} HIGH severity findings. Implement missing email security "
             f"controls (SPF/DKIM/DMARC), review DNS records for takeover vulnerabilities, "
             f"and add missing HTTP security headers."),
            ("Phase 3 — Medium Term (30–90 days)", C_MEDIUM,
             "Deploy continuous monitoring via attack surface management tools. "
             "Implement SIEM alerting for Shodan changes. Set up GitHub secret scanning in CI/CD pipelines."),
            ("Phase 4 — Ongoing", C_LOW,
             "Schedule quarterly attack surface reviews. Integrate DMARC reporting, "
             "automated subdomain monitoring, and vulnerability disclosure program."),
        ]

        for title, color, desc in phases:
            data = [[Paragraph(title, ParagraphStyle(
                "phase_t", fontName="Helvetica-Bold", fontSize=11, textColor=color
            ))], [Paragraph(desc, s["body"])]]
            t = Table(data, colWidths=[17*cm])
            t.setStyle(TableStyle([
                ("BACKGROUND", (0,0), (-1,-1), C_SURFACE),
                ("LEFTPADDING", (0,0), (-1,-1), 12),
                ("RIGHTPADDING", (0,0), (-1,-1), 12),
                ("TOPPADDING", (0,0), (-1,-1), 8),
                ("BOTTOMPADDING", (0,0), (-1,-1), 8),
                ("LINEBEFORE", (0,0), (0,-1), 4, color),
            ]))
            elements.append(t)
            elements.append(Spacer(1, 0.4*cm))

        return elements

    def _appendix(self):
        s = self._styles()
        elements = [PageBreak(), Paragraph("Appendix — ML Feature Vector", s["h1"])]
        elements.append(HRFlowable(width="100%", thickness=1, color=C_ACCENT))
        elements.append(Spacer(1, 0.3*cm))
        elements.append(Paragraph(
            "The following feature vector was used as input to the ML risk scoring model. "
            "These features are derived from raw OSINT data and normalized for scoring.",
            s["body"]
        ))
        elements.append(Spacer(1, 0.3*cm))

        features = self.scores.get("ml_features", {})
        rows = [["Feature", "Value", "Description"]]
        feature_desc = {
            "f_subdomain_count": "Number of active subdomains discovered",
            "f_zone_transfer_enabled": "DNS zone transfer allowed (0/1)",
            "f_wildcard_dns": "Wildcard DNS record present (0/1)",
            "f_open_ports": "Total open ports found via Shodan",
            "f_critical_cves": "CVEs with CVSS score ≥ 9.0",
            "f_high_cves": "CVEs with CVSS score 7.0–8.9",
            "f_github_leaks": "Leaked secrets found on GitHub",
            "f_public_repos": "Public repos with sensitive matches",
            "f_email_score": "Email security score (0-100, higher=better)",
            "f_spf_present": "SPF record exists (0/1)",
            "f_dmarc_present": "DMARC record exists (0/1)",
            "f_dkim_present": "DKIM selector found (0/1)",
            "f_missing_headers": "Count of missing HTTP security headers",
            "f_version_disclosed": "Server version in HTTP headers (0/1)",
            "f_cert_issues": "SSL certificate issues count",
        }
        for feat, val in features.items():
            rows.append([feat, str(val), feature_desc.get(feat, "")])

        t = Table(rows, colWidths=[5*cm, 2*cm, 10*cm])
        t.setStyle(TableStyle([
            ("BACKGROUND", (0,0), (-1,0), C_ACCENT),
            ("TEXTCOLOR", (0,0), (-1,0), black),
            ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),
            ("FONTSIZE", (0,0), (-1,-1), 8),
            ("FONTNAME", (0,1), (0,-1), "Courier"),
            ("TEXTCOLOR", (0,1), (0,-1), HexColor("#A8FF78")),
            ("TEXTCOLOR", (1,1), (-1,-1), C_TEXT),
            ("TOPPADDING", (0,0), (-1,-1), 5),
            ("BOTTOMPADDING", (0,0), (-1,-1), 5),
            ("LEFTPADDING", (0,0), (-1,-1), 8),
            ("ROWBACKGROUNDS", (0,1), (-1,-1), [C_BG, C_SURFACE]),
            ("GRID", (0,0), (-1,-1), 0.3, C_MUTED),
        ]))
        elements.append(t)
        return elements

    def _generate_text_report(self, path: str) -> str:
        """Fallback plain text report."""
        with open(path, "w") as f:
            f.write(f"CORPORATE ATTACK SURFACE REPORT\n")
            f.write(f"{'='*60}\n")
            f.write(f"Target: {self.domain}\n")
            f.write(f"Company: {self.company}\n")
            f.write(f"Date: {datetime.utcnow().isoformat()}\n\n")
            f.write(f"OVERALL RISK SCORE: {self.scores.get('overall', 0):.1f}/100\n")
            f.write(f"RISK LEVEL: {self.scores.get('risk_label', 'UNKNOWN')}\n\n")
            f.write("TOP RISKS:\n")
            for risk in self.scores.get("top_risks", [])[:10]:
                f.write(f"  [{risk.get('severity')}] {risk.get('title')}\n")
                f.write(f"  → {risk.get('recommendation')}\n\n")
        return path